### ISSUE TITLE
AbstractProcessStage will attempt to persist discarded documents

### ISSUE THREAD

**Issue by jwestberg** [Findwise/Hydra#146] opened 2012-12-20 10:57 UTC
When running a DocumentDiscardStage, for instance, that marks a document as discarded, the AbstractProcessStage will still attempt to persist any changes and release the document (e.g. mark it touched), but of course this will fail since the document is no longer available. This results in an error being logged for every document discarded:

```
[Thread-14] ERROR discardStage - Node gave an unexpected response: HTTP/1.1 404 Not Found
[Thread-14] ERROR discardStage - Message: No document found matching your query
[Thread-14] ERROR discardStage - Unable to persist an error to the database
java.io.IOException: Unable to save changes to core
    at com.findwise.hydra.stage.AbstractProcessStage.run(AbstractProcessStage.java:114)
```

This is a little non-trivial to fix, especially since LocalDocuments cant be compared by ID via the standard equals method (they, as it turns out, are Map representations of MongoDBs ObjectID)

**Comment by laserval** [comment] 2013-02-05 13:31
This has no actual implications on the document, it just causes an error to be written in the log.

**Comment by laserval** [comment] 2013-12-04 15:04
Closing as duplicate of #226 which has more information and discussion.

**Closed as completed by laserval** 2013-12-04 15:04 UTC
Labels: bug, duplicate, stages
